cargo-features = ["edition2024"]

[dependencies]
# console-subscriber = "0.4.0"
clap = {workspace = true, features = ["derive"]}
dotenvy = "0.15.7"
ndarray = "0.16.1"
serde_json = "1.0.128"
anyhow.workspace = true
compact_str.workspace = true
fastrand.workspace = true
flecs_ecs.workspace = true
hyperion.workspace = true
hyperion-inventory.workspace = true
hyperion-permission.workspace = true
hyperion-scheduled.workspace = true
hyperion-text.workspace = true
hyperion-utils.workspace = true
nom.workspace = true
roaring.workspace = true
rustc-hash.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tracy.workspace = true

[dev-dependencies]
tokio = {workspace = true, features = ["full"]}
tracing = {workspace = true, features = ["release_max_level_info"]}

[lints]
workspace = true

[package]
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
edition = "2024"
name = "proof-of-concept"
publish = false
readme = "README.md"
version = "0.1.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator.workspace = true
