cargo-features = ["edition2024"]

[dependencies]
anyhow.workspace = true
clap = {workspace = true, features = ["derive"]}
compact_str.workspace = true
dotenvy = "0.15.7"
fastrand.workspace = true
flecs_ecs.workspace = true
hyperion-clap.workspace = true
hyperion-inventory.workspace = true
hyperion-permission.workspace = true
hyperion-scheduled.workspace = true
hyperion-text.workspace = true
hyperion-utils.workspace = true
hyperion-rank-tree.workspace = true
hyperion.workspace = true
roaring.workspace = true
rustc-hash.workspace = true
tracing-subscriber.workspace = true
tracing-tracy.workspace = true
tracing.workspace = true
rayon.workspace = true
gxhash.workspace = true
derive_more.workspace = true

[dev-dependencies]
tracing = {workspace = true, features = ["release_max_level_info"]}

[lints]
workspace = true

[package]
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
edition = "2024"
name = "proof-of-concept"
publish = false
readme = "README.md"
version = "0.1.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator.workspace = true
