[package]
name = "proof-of-concept"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
anyhow.workspace = true
#console-subscriber = "0.4.0"
clap = { workspace = true, features = ["derive"] }
compact_str.workspace = true
dotenvy = "0.15.7"
fastrand.workspace = true
flecs_ecs.workspace = true
hyperion-inventory.workspace = true
hyperion-scheduled.workspace = true
hyperion-text.workspace = true
hyperion-utils.workspace = true
roaring.workspace = true
hyperion.workspace = true
ndarray = "0.16.1"
nom = "7.1.3"
rustc-hash.workspace = true
serde_json = "1.0.128"
tracing-subscriber.workspace = true
tracing.workspace = true
[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["release_max_level_info"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator.workspace = true

[lints]
workspace = true
