[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[features]
trace = []
full = ["trace"]
pprof = ["dep:pprof"]
trace-simple = []
default = ["trace-simple"]


[dependencies]
anyhow = "1.0.81"
tracing = "0.1.40"
serde_json = "1.0.114"
bytes = "1.6.0"

# get terminated by signal SIGBUS (Misaligned address error) without frame-pointer
pprof = { version =  "0.13.0", optional = true , features = ["flamegraph", "frame-pointer"] }

valence_protocol = { git = "https://github.com/valence-rs/valence" }
valence_registry = { git = "https://github.com/valence-rs/valence" }

generator.workspace = true

chunk.workspace = true


# no secure alloc
sha2 = "0.10.8"
itertools = "0.12.1"
rand = "0.8.5"
evenio.workspace = true
flume = "0.11.0"

# todo: how much will adding "sync" wakers hurt performance?
monoio = { version = "0.2.3", features = ["sync"] }
signal-hook = "0.3.17"
base64 = "0.22.0"
uuid = "1.8.0"
rand_distr = "0.4.3"
smallvec = { git = "https://github.com/servo/rust-smallvec" }
fnv = "1.0.7"
rayon = "1.10.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-flame = "0.2.0"
ndarray = "0.15.6"
jemallocator = "0.5.4"
jemalloc-ctl = "0.5.4"
libc = "0.2.153"
fastrand = "2.0.2"
spin = "0.9.8"
rayon-local.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6.3"


[dev-dependencies]
#criterion = { version = "0.5.1", features = ["html_reports"] }
divan = "0.1.14"
#tango-bench = "0.4.0"
#iai = "0.1"
#iai-callgrind = "0.10.2"
thread-priority = "0.16.0"

# removing this because jemalloc-ctl is nice for memory stats also
# https://github.com/rust-lang/rust-analyzer/issues/1441#issuecomment-509506279
# jemalloc uses significantly less memory
#mimalloc = { version = "0.1.39" , default-features = false }


[[bench]]
name = "many_zombies"
harness = false

[lints.clippy]
complexity = "deny"

nursery = { level = "deny", priority = -1 }
redundant_pub_crate = "allow"

pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"

# restriction
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
unwrap_used = "deny"
