[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[package.metadata.cargo-machete]
ignored = ["flate2"]

[features]
trace = ["dep:tracing-subscriber"]
full = ["trace"]
pprof = ["dep:pprof"]
tracy = ["dep:tracing-tracy", "dep:tracing-subscriber"]
trace-simple = ["dep:tracing-subscriber"]
default = ["trace-simple"]


[dependencies]
anyhow = "1.0.81"
tracing = "0.1.40"
serde_json = "1.0.115"
bytes = "1.6.0"

# get terminated by signal SIGBUS (Misaligned address error) without frame-pointer
pprof = { version =  "0.13.0", optional = true , features = ["flamegraph", "frame-pointer"] }

valence_protocol = { git = "https://github.com/valence-rs/valence", features = ["compression"] }
valence_registry = { git = "https://github.com/valence-rs/valence" }

generator.workspace = true

chunk.workspace = true


# no secure alloc
sha2 = "0.10.8"
itertools = "0.12.1"
rand = "0.8.5"
evenio.workspace = true
flume = "0.11.0"

# todo: how much will adding "sync" wakers hurt performance?
monoio = { version = "0.2.3", features = ["sync"] }
signal-hook = "0.3.17"
base64 = "0.22.0"
uuid = { version = "1.8.0", features = ["v3"] }
rand_distr = "0.4.3"
smallvec.workspace = true
rayon = "1.10.0"
tracing-subscriber = { version = "0.3.18", features = ["chrono", "env-filter"], optional = true }
tracing-flame = "0.2.0"
ndarray = "0.15.6"
libc = "0.2.153"
spin = "0.9.8"
rayon-local.workspace = true
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
bvh.workspace = true
glam.workspace = true
once_cell = "1.19.0"
spin_sleep = "1.2.0"
tracing-tracy = { version = "0.11.0" , optional = true }
fastrand = "2.0.2"
no_denormals = "0.1.2"
derive-build = "0.1.1"
flate2 = { version = "1.0.28", features = ["zlib-ng"], default-features = false }
arrayvec = "0.7.4"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6.3"


[dev-dependencies]
divan = "0.1.14"
rust-mc-bot.workspace = true
tango-bench = "0.4.0"

[[bench]]
name = "many_zombies"
harness = false

[[bench]]
name = "players"
harness = false

[lints.clippy]
complexity = "deny"

nursery = { level = "deny", priority = -1 }
redundant_pub_crate = "allow"

pedantic = { level = "deny", priority = -1 }
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
missing_errors_doc = "allow"

perf = "deny"
style = "deny"
suspicious = "deny"

# restriction
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
